"""Unit tests for webapp/analysis.py.

The synthetic ECG + PPG generated by conftest produce realistic peak
counts (~30 R-peaks in 30 s @ 60 BPM), enough matched beats for
compute_ccc to return a real number, and a positively-skewed PPG so
SSQI / interpretation lines all fire.
"""

import os

import numpy as np
import pytest

from webapp import analysis, sessions


# ── Loaders ─────────────────────────────────────────────────────────────────

class TestLoaders:

    def test_load_ecg_returns_three_arrays(self, synth_session):
        _, sdir, _ = synth_session
        ts_ms, sig, leads_off = analysis.load_ecg(
            os.path.join(sdir, "ecg_data.csv"))
        assert len(ts_ms) == len(sig) == len(leads_off)
        assert len(ts_ms) > 0
        # ts_us → ms conversion in the loader: the writer scales the
        # ts_us by 1_000_000, so ts_ms should be at least that big.
        assert ts_ms[0] >= 1e6
        # Leads-off column is always int.
        assert leads_off.dtype.kind in ("i", "u")

    def test_load_ppg_returns_two_arrays(self, synth_session):
        _, sdir, _ = synth_session
        ts_ms, sig = analysis.load_ppg(
            os.path.join(sdir, "ppg_data_ch0.csv"))
        assert len(ts_ms) == len(sig)
        assert len(ts_ms) > 0

    def test_load_ppg_skips_non_numeric_rows(self, tmp_path):
        """The loader uses on_bad_lines='skip' + to_numeric coercion;
        a stray header or partial flush mustn't poison the array."""
        path = tmp_path / "ppg.csv"
        with open(path, "w") as f:
            f.write("100,1.0\n200,2.0\nnot,a,number\n400,4.0\n")
        ts_ms, sig = analysis.load_ppg(str(path))
        # The "not,a,number" row has 3 cols — read_csv will skip or
        # to_numeric will drop it. Either way the valid rows survive.
        assert len(ts_ms) >= 3
        assert not np.isnan(ts_ms).any()


# ── ppg_bandpass guard rails ────────────────────────────────────────────────

class TestPpgBandpass:

    def test_normal_returns_same_shape(self):
        rng = np.random.default_rng(0)
        sig = rng.standard_normal(2000)
        out = analysis.ppg_bandpass(sig, fs=200.0)
        assert out is not None
        assert out.shape == sig.shape

    def test_nan_fs_returns_none(self):
        sig = np.ones(2000)
        assert analysis.ppg_bandpass(sig, fs=float("nan")) is None

    def test_zero_fs_returns_none(self):
        sig = np.ones(2000)
        assert analysis.ppg_bandpass(sig, fs=0.0) is None

    def test_too_short_returns_none(self):
        # filtfilt padlen = 3*max(len(a), len(b)) = 15 for the
        # 0.5-8 Hz Butterworth order-2 we use; signal must be <= 15.
        sig = np.ones(10)
        assert analysis.ppg_bandpass(sig, fs=200.0) is None

    def test_cutoffs_above_nyquist_return_none(self):
        sig = np.ones(2000)
        # fs=1 Hz means Nyquist=0.5 Hz; default highcut=8.0 Hz is above it.
        assert analysis.ppg_bandpass(sig, fs=1.0) is None


# ── infer_fs ────────────────────────────────────────────────────────────────

class TestInferFs:

    def test_uniform_sampling(self):
        ts_ms = np.arange(0, 1000, 5.0)   # 5 ms step => 200 Hz
        assert analysis.infer_fs(ts_ms) == pytest.approx(200.0)

    def test_too_few_samples_returns_nan(self):
        assert np.isnan(analysis.infer_fs(np.array([])))
        assert np.isnan(analysis.infer_fs(np.array([1.0])))

    def test_zero_dt_returns_nan(self):
        ts_ms = np.array([100.0, 100.0, 100.0])
        assert np.isnan(analysis.infer_fs(ts_ms))


# ── effective_fs ─────────────────────────────────────────────────────────────

class TestEffectiveFs:

    def test_uniform_matches_infer_fs(self):
        ts_ms = np.arange(0, 1000, 5.0)   # 5 ms step => 200 Hz
        assert analysis.effective_fs(ts_ms) == pytest.approx(200.0)

    def test_bimodal_reports_true_throughput_not_median(self):
        # 60% of gaps are 2.5 ms (400 Hz), 40% are 10 ms (100 Hz) — the same
        # majority-fast shape the real starved-ECG recordings show. The median
        # gap lands in the fast cluster so infer_fs reports ~400 Hz, but the
        # actual average rate over the span is far lower. effective_fs must
        # reflect the real throughput, not the dominant-mode cadence.
        gaps = np.concatenate([np.full(600, 2.5), np.full(400, 10.0)])
        ts_ms = np.concatenate([[0.0], np.cumsum(gaps)])
        assert analysis.infer_fs(ts_ms) == pytest.approx(400.0)
        span_s = ts_ms[-1] / 1000.0
        expected = (len(ts_ms) - 1) / span_s
        assert analysis.effective_fs(ts_ms) == pytest.approx(expected)
        assert analysis.effective_fs(ts_ms) < 200.0

    def test_too_few_samples_returns_nan(self):
        assert np.isnan(analysis.effective_fs(np.array([])))
        assert np.isnan(analysis.effective_fs(np.array([1.0])))

    def test_zero_span_returns_nan(self):
        assert np.isnan(analysis.effective_fs(np.array([5.0, 5.0, 5.0])))


# ── _downsample preserves extremes ─────────────────────────────────────────

class TestDownsample:

    def test_short_signal_passes_through(self):
        x = np.arange(50, dtype=float)
        y = np.sin(x)
        xs, ys = analysis._downsample(x, y, max_points=100)
        assert len(xs) == len(x)
        np.testing.assert_array_equal(xs, x)

    def test_max_points_zero_passes_through(self):
        x = np.arange(50, dtype=float)
        y = np.sin(x)
        xs, ys = analysis._downsample(x, y, max_points=0)
        assert len(xs) == len(x)

    def test_extreme_preserved(self):
        """The min/max bucket scheme exists to keep R-peaks visible
        after decimation. Embed a sharp spike and confirm it survives."""
        x = np.arange(2000, dtype=float)
        y = np.zeros(2000)
        y[1000] = 99.0    # sharp positive spike
        y[1500] = -50.0   # sharp negative spike
        xs, ys = analysis._downsample(x, y, max_points=200)
        # Both the global max and global min should land in the output.
        assert 99.0 in ys
        assert -50.0 in ys

    def test_x_remains_monotonic(self):
        """Front-end interpY needs strictly-increasing x."""
        x = np.arange(2000, dtype=float)
        y = np.sin(x / 50.0)
        xs, ys = analysis._downsample(x, y, max_points=200)
        assert (np.diff(xs) >= 0).all()


# ── interpret_channel structure ─────────────────────────────────────────────

class TestInterpretChannel:

    def _row(self, **overrides):
        base = {
            "channel": 0,
            "site": "finger",
            "ssqi": 1.2,
            "zsqi_mean": 0.04,
            "zsqi_std": 0.01,
            "n_matched_beats": 50,
            "n_rr_intervals": 60,
            "n_ppi_intervals": 58,
            "stats": {
                "ccc": 0.96,
                "icc": 0.95,
                "bias_ms": 50.0,
                "loa_lower_ms": -100.0,
                "loa_upper_ms": 200.0,
                "rmse_ms": 30.0,
            },
        }
        base.update(overrides)
        return base

    def test_good_channel_has_required_keys(self):
        out = analysis.interpret_channel(self._row())
        for k in ("verdict", "grade", "lines", "advice"):
            assert k in out
        assert isinstance(out["lines"], list) and len(out["lines"]) > 0
        assert out["grade"] in ("good", "ok", "warn", "bad")

    def test_zero_matched_beats_grades_bad(self):
        out = analysis.interpret_channel(self._row(
            n_matched_beats=0, stats=None))
        assert out["grade"] == "bad"
        # The advice line should mention contact / threshold troubleshooting.
        assert "contact" in out["advice"].lower() or "threshold" in out["advice"].lower()

    def test_good_ccc_yields_good_grade(self):
        out = analysis.interpret_channel(self._row())
        # ccc 0.96, ssqi 1.2 => "good"
        assert out["grade"] == "good"

    def test_low_ccc_yields_warn_or_bad(self):
        out = analysis.interpret_channel(self._row(
            stats={"ccc": 0.6, "icc": 0.5, "bias_ms": 50.0,
                   "loa_lower_ms": -50, "loa_upper_ms": 50, "rmse_ms": 10}))
        assert out["grade"] in ("warn", "bad")

    def test_small_matched_count_downgrades(self):
        """Even with good CCC, fewer than 30 matched beats should
        downgrade the grade to warn."""
        out = analysis.interpret_channel(self._row(n_matched_beats=10))
        assert out["grade"] == "warn"


# ── interpret_session structure ─────────────────────────────────────────────

class TestInterpretSession:

    def test_required_keys(self):
        ecg = {"fs_hz": 250.0, "n_samples": 7500, "duration_s": 30.0,
               "n_peaks": 30, "mean_hr_bpm": 60.0, "leads_off_samples": 0}
        results = [{
            "channel": 0, "site": "finger",
            "ssqi": 1.2, "zsqi_mean": 0.04, "zsqi_std": 0.01,
            "n_matched_beats": 50,
            "n_rr_intervals": 60, "n_ppi_intervals": 58,
            "stats": {
                "ccc": 0.96, "icc": 0.95, "bias_ms": 50.0,
                "loa_lower_ms": -100, "loa_upper_ms": 200, "rmse_ms": 30,
            },
        }]
        out = analysis.interpret_session(ecg, results)
        for k in ("headline", "ecg_text", "channel_summaries",
                  "best_channel", "worst_channel", "notes"):
            assert k in out
        assert out["best_channel"] == 0

    def test_empty_results_handles_gracefully(self):
        ecg = {"fs_hz": 250.0, "n_samples": 0, "duration_s": 0.0,
               "n_peaks": 0, "mean_hr_bpm": float("nan"),
               "leads_off_samples": 0}
        out = analysis.interpret_session(ecg, [])
        assert out["best_channel"] is None
        assert out["worst_channel"] is None
        assert isinstance(out["channel_summaries"], list)


# ── interpret_batch structure ───────────────────────────────────────────────

class TestInterpretBatch:

    def test_empty_per_site_returns_headline(self):
        out = analysis.interpret_batch([], [], [], fst_unavailable=True)
        assert "headline" in out
        assert "site_summaries" in out
        assert "notes" in out

    def test_with_sites_produces_summaries(self):
        per_site = [{
            "site": "finger", "n_channels": 3,
            "matched_beats_total": 90,
            "ccc": {"mean": 0.95, "std": 0.02, "n": 3},
            "ssqi": {"mean": 1.0, "std": 0.1, "n": 3},
            "bias_ms": {"mean": 50.0, "std": 5.0, "n": 3},
        }, {
            "site": "forehead", "n_channels": 3,
            "matched_beats_total": 80,
            "ccc": {"mean": 0.7, "std": 0.05, "n": 3},
            "ssqi": {"mean": 0.3, "std": 0.1, "n": 3},
            "bias_ms": {"mean": 100.0, "std": 10.0, "n": 3},
        }]
        out = analysis.interpret_batch(
            per_session=[{"results": []}], per_site=per_site,
            failed=[], fst_unavailable=True)
        assert len(out["site_summaries"]) == 2
        # FST-missing note must be present.
        assert any("Fitzpatrick" in n for n in out["notes"])

    def test_failed_sessions_surfaced_in_notes(self):
        per_site = [{
            "site": "finger", "n_channels": 1,
            "matched_beats_total": 10,
            "ccc": {"mean": 0.95, "std": 0.0, "n": 1},
            "ssqi": {"mean": 1.0, "std": 0.0, "n": 1},
            "bias_ms": {"mean": 0.0, "std": 0.0, "n": 1},
        }]
        out = analysis.interpret_batch(
            per_session=[], per_site=per_site,
            failed=[{"name": "session_X", "error": "missing ECG"}],
            fst_unavailable=False)
        assert any("Failed sessions" in n for n in out["notes"])


# ── _safe_icc ───────────────────────────────────────────────────────────────

class TestSafeIcc:

    def test_too_few_returns_none(self):
        rr = np.array([800.0, 810.0])
        ppi = np.array([850.0, 860.0])
        # Need at least 4 matched beats.
        assert analysis._safe_icc(rr, ppi) is None

    def test_valid_input_returns_dict_if_pingouin_available(self):
        pytest.importorskip("pingouin")
        rng = np.random.default_rng(0)
        rr = 1000.0 + 30.0 * rng.standard_normal(20)
        ppi = rr + 5.0 * rng.standard_normal(20)
        out = analysis._safe_icc(rr, ppi)
        # Pingouin may legitimately fail on a pathological input
        # (returns None) — but a clean, correlated pair should succeed.
        if out is None:
            pytest.skip("pingouin returned None for valid input — env-specific")
        assert set(out.keys()) >= {"icc", "ci_low", "ci_high", "n"}
        assert out["n"] == 20
        assert 0.0 <= out["icc"] <= 1.0


# ── _aggregate_per_site math ────────────────────────────────────────────────

class TestAggregatePerSite:

    def _row(self, site, ccc=0.9, ssqi=1.0, n_matched=50):
        return {
            "_session_name": "session_20260101_120000",
            "site": site,
            "ssqi": ssqi,
            "zsqi_mean": 0.04, "zsqi_std": 0.01,
            "n_matched_beats": n_matched,
            "stats": {
                "ccc": ccc, "icc": ccc, "pearson_r": ccc,
                "bias_ms": 50.0,
                "loa_lower_ms": -100.0, "loa_upper_ms": 100.0,
                "rmse_ms": 25.0, "mae_ms": 20.0,
            },
        }

    def test_groups_by_site(self):
        per_session = [{"results": [
            self._row("finger", ccc=0.9),
            self._row("forehead", ccc=0.85),
        ]}]
        out = analysis._aggregate_per_site(per_session)
        sites = sorted(s["site"] for s in out)
        assert sites == ["finger", "forehead"]

    def test_rows_follow_mux_lane_order_not_alphabetical(self):
        """Rows read finger-first (ch0 → ch4), matching the per-channel
        tables. Alphabetical would lead with earlobe."""
        per_session = [{"results": [self._row(s) for s in
                        ("wrist", "earlobe", "forehead", "finger", "shoulder")]}]
        out = analysis._aggregate_per_site(per_session)
        assert [r["site"] for r in out] == [
            "finger", "earlobe", "shoulder", "forehead", "wrist"]

    def test_unknown_sites_sort_after_known_ones(self):
        """A hand-edited site label must still appear — alphabetically,
        after every site in the default mux map."""
        per_session = [{"results": [self._row(s) for s in
                        ("zebra", "finger", "abacus", "wrist")]}]
        out = analysis._aggregate_per_site(per_session)
        assert [r["site"] for r in out] == ["finger", "wrist", "abacus", "zebra"]

    def test_mean_std_correctness(self):
        per_session = [{"results": [
            self._row("finger", ccc=0.9),
            self._row("finger", ccc=0.95),
            self._row("finger", ccc=1.0),
        ]}]
        out = analysis._aggregate_per_site(per_session)
        assert len(out) == 1
        row = out[0]
        assert row["n_channels"] == 3
        ccc = row["ccc"]
        assert ccc["mean"] == pytest.approx(0.95)
        # ddof=1 sample std of [0.9, 0.95, 1.0] = 0.05
        assert ccc["std"] == pytest.approx(0.05)
        assert ccc["n"] == 3

    def test_mean_std_drops_non_finite(self):
        per_session = [{"results": [
            self._row("finger", ccc=0.9),
            self._row("finger", ccc=float("nan")),
            self._row("finger", ccc=0.92),
        ]}]
        out = analysis._aggregate_per_site(per_session)
        ccc = out[0]["ccc"]
        # The NaN row is excluded from the mean/std/n.
        assert ccc["n"] == 2
        assert ccc["mean"] == pytest.approx(0.91)

    def test_empty_results_returns_empty(self):
        assert analysis._aggregate_per_site([]) == []

    def test_unassigned_site_grouping(self):
        per_session = [{"results": [
            self._row(""),               # falsy site
            self._row(None),
            self._row("finger"),
        ]}]
        out = analysis._aggregate_per_site(per_session)
        sites = sorted(s["site"] for s in out)
        # Empty / None roll up into "unassigned".
        assert "unassigned" in sites
        assert "finger" in sites


# ── Frequency-domain HRV (Welch PSD) ────────────────────────────────────────

class TestFreqDomainMetrics:
    """_freq_domain_metrics replaced a pyhrv call with scipy.signal.welch.
    A sinusoid of amplitude A carries variance A²/2, and integrating the PSD
    over its band recovers exactly that — so a synthetic NN series with known
    LF and HF components pins the absolute calibration, not just the shape."""

    def _nn(self, lf_amp=30.0, hf_amp=15.0, n=400, mean_ms=800.0):
        # Beat times advance by ~mean_ms, so modulate in beat-time seconds.
        t_s = np.cumsum(np.full(n, mean_ms / 1000.0))
        return (mean_ms
                + lf_amp * np.sin(2 * np.pi * 0.10 * t_s)     # inside LF
                + hf_amp * np.sin(2 * np.pi * 0.25 * t_s))    # inside HF

    def test_band_powers_match_sinusoid_variance(self):
        out = analysis._freq_domain_metrics(self._nn())
        # A²/2: 30 -> 450 ms², 15 -> 112.5 ms². 10% tolerance covers
        # windowing leakage and the linear detrend.
        assert out["lf_power_ms2"] == pytest.approx(450.0, rel=0.1)
        assert out["hf_power_ms2"] == pytest.approx(112.5, rel=0.1)
        assert out["lf_hf_ratio"] == pytest.approx(4.0, rel=0.15)

    def test_ratio_tracks_lf_hf_balance(self):
        hf_heavy = analysis._freq_domain_metrics(self._nn(lf_amp=10.0, hf_amp=40.0))
        assert hf_heavy["lf_hf_ratio"] < 1.0

    def test_short_series_returns_nan_not_raise(self):
        out = analysis._freq_domain_metrics(np.full(10, 800.0))
        assert all(np.isnan(v) for v in out.values())

    def test_constant_nn_has_no_band_power(self):
        # A perfectly regular heartbeat has no variability to distribute.
        out = analysis._freq_domain_metrics(np.full(400, 800.0))
        assert out["lf_power_ms2"] == pytest.approx(0.0, abs=1e-6)


# ── Skin-tone stratification ────────────────────────────────────────────────

class TestStratifyBySkin:

    def _session(self, fst, ccc=0.9):
        row = {
            "_session_name": f"session_fst{fst}",
            "site": "finger", "ssqi": 1.0, "ksqi": 2.1,
            "zsqi_mean": 0.04, "zsqi_std": 0.01, "n_matched_beats": 50,
            "channel": 0, "mean_hr_bpm": 70.0, "sdnn_ms": 40.0, "lf_hf_ratio": 1.2,
            "stats": {
                "ccc": ccc, "icc": ccc, "pearson_r": ccc, "bias_ms": 50.0,
                "loa_lower_ms": -100.0, "loa_upper_ms": 100.0,
                "rmse_ms": 25.0, "mae_ms": 20.0,
            },
        }
        return {
            "participant": {"fitzpatrick": fst},
            "ecg": {"mean_hr_bpm": 70.0, "sdnn_ms": 40.0, "lf_hf_ratio": 1.2},
            "results": [row],
        }

    def test_group_boundaries(self):
        assert analysis._skin_group_of(1) == "light"
        assert analysis._skin_group_of(2) == "light"
        assert analysis._skin_group_of(3) == "medium"
        assert analysis._skin_group_of(4) == "medium"
        assert analysis._skin_group_of(5) == "dark"
        assert analysis._skin_group_of(6) == "dark"
        assert analysis._skin_group_of(0) is None
        assert analysis._skin_group_of(7) is None
        assert analysis._skin_group_of(None) is None

    def test_always_three_bands(self):
        out = analysis._stratify_by_skin([])
        assert [g["group"] for g in out] == ["light", "medium", "dark"]
        assert all(g["n_sessions"] == 0 for g in out)
        for g in out:
            for k in ("per_site", "hr_per_channel", "sdnn_per_channel", "lfhf_per_channel"):
                assert g[k] == []

    def test_buckets_by_fst(self):
        per_session = [self._session(1), self._session(2),
                       self._session(4), self._session(6)]
        out = {g["group"]: g for g in analysis._stratify_by_skin(per_session)}
        assert out["light"]["n_sessions"] == 2
        assert out["medium"]["n_sessions"] == 1
        assert out["dark"]["n_sessions"] == 1
        # Light band saw 2 sessions at one site → per-site aggregate present.
        assert out["light"]["per_site"][0]["site"] == "finger"
        assert out["light"]["per_site"][0]["n_sessions"] == 2

    def test_ungraded_sessions_dropped(self):
        per_session = [self._session(None), self._session(2)]
        out = {g["group"]: g for g in analysis._stratify_by_skin(per_session)}
        assert out["light"]["n_sessions"] == 1
        assert sum(g["n_sessions"] for g in out.values()) == 1


# ── End-to-end: analyze_session against synthetic data ──────────────────────

class TestAnalyzeSessionEndToEnd:

    def test_full_pipeline_returns_expected_shape(self, synth_session):
        name, _, _ = synth_session
        out = analysis.analyze_session(name)
        assert "ecg" in out
        assert "results" in out
        assert "interpretation" in out
        assert "participant" in out
        assert len(out["results"]) == 3   # synth has 3 channels
        for row in out["results"]:
            for k in ("channel", "site", "ssqi", "ksqi", "zsqi_mean",
                      "n_matched_beats", "interpretation"):
                assert k in row
        # ECG block:
        ecg = out["ecg"]
        # Synthetic data gives ~30 R-peaks for 30 s @ 60 BPM.
        assert ecg["n_peaks"] > 20
        assert 50 < ecg["mean_hr_bpm"] < 80

    def test_uses_default_site_map_when_no_metadata(self, synth_session):
        name, _, _ = synth_session
        out = analysis.analyze_session(name)
        # No participant.json was written, so default site map applies.
        site_for_ch0 = next(r["site"] for r in out["results"] if r["channel"] == 0)
        assert site_for_ch0 == "finger"

    def test_uses_explicit_metadata_when_provided(
            self, synth_session_with_metadata):
        name, _, _, _ = synth_session_with_metadata
        out = analysis.analyze_session(name)
        site_for_ch2 = next(r["site"] for r in out["results"] if r["channel"] == 2)
        # Explicit map sets ch2 -> "wrist".
        assert site_for_ch2 == "wrist"

    def test_crop_window_shrinks_duration(self, synth_session):
        name, _, _ = synth_session
        full = analysis.analyze_session(name)
        cropped = analysis.analyze_session(name, start_s=5.0, end_s=15.0)
        # Cropped window is 10 s ⇒ duration should reflect it (within
        # the sample resolution).
        assert cropped["ecg"]["duration_s"] < full["ecg"]["duration_s"]
        assert cropped["ecg"]["duration_s"] == pytest.approx(10.0, abs=0.1)

    def test_missing_session_returns_error(self, isolated_sessions_root):
        out = analysis.analyze_session("session_99990101_000000")
        assert "error" in out
